language: node_js

node_js:
  - 8

branches:
  only:
    - master

cache: yarn

env:
  global:

before_install:
  - echo "//registry.npmjs.com/:_authToken=\${NPM_TOKEN}" > .npmrc
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

script:
  - make run

after_script:
  - tc-builder slack-notify
